name: Test Planets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_planets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Give execute permission to Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Run planet tests
      run: npm test -- --testPathPattern=planets
