name: Test 404 Endpoints

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_404:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run 404 tests
      run: npm test -- --testPathPattern=404
